import type { AstroIntegration } from 'astro';

/**
 * Options for the Routify Astro integration.
 */
export interface RoutifyOptions {
    /**
     * The directory to scan for route files.
     * @default 'src'
     */
    routesDir?: string;

    /**
     * The glob pattern(s) to match route files.
     * @default '**\/*.{route,routes}.{ts,js,mts,mjs}'
     */
    pattern?: string | string[];

    /**
     * If true, enables debug logging for the integration.
     * @default false
     */
    debug?: boolean;
}

/**
 * An Astro integration that automatically discovers and registers routes.
 * 
 * This eliminates the need to manually call `import.meta.glob` in your 
 * API entry point. Just add `routify()` to your `astro.config.mjs` and
 * use `createRouter()` without arguments.
 * 
 * @example
 * // astro.config.mjs
 * import { routify } from 'astro-routify';
 * export default defineConfig({
 *   integrations: [routify()]
 * });
 * 
 * @param options - Configuration for the integration.
 * @returns An Astro integration object.
 */
export function routify(options: RoutifyOptions = {}): AstroIntegration {
    const {
        routesDir = 'src',
        pattern = '**/*.{route,routes}.{ts,js,mts,mjs}',
        debug = false
    } = options;

    const virtualModuleId = 'virtual:astro-routify/auto-register';
    const resolvedVirtualModuleId = '\0' + virtualModuleId;

    return {
        name: 'astro-routify',
        hooks: {
            'astro:config:setup': ({ updateConfig }) => {
                if (debug) {
                    console.log(`\x1b[36m[astro-routify]\x1b[0m Integration initialized. Scanning ${routesDir} for ${pattern}`);
                }

                updateConfig({
                    vite: {
                        plugins: [
                            {
                                name: 'vite-plugin-astro-routify',
                                resolveId(id) {
                                    if (id === virtualModuleId) {
                                        return resolvedVirtualModuleId;
                                    }
                                    return null;
                                },
                                load(id) {
                                    if (id === resolvedVirtualModuleId) {
                                        const patterns = Array.isArray(pattern) ? pattern : [pattern];
                                        // Use absolute paths from project root for the glob
                                        const globPatterns = patterns.map(p => `/${routesDir.replace(/^\/+/, '')}/${p.replace(/^\/+/, '')}`);
                                        
                                        return `
                                            /** Auto-generated by astro-routify */
                                            export const modules = import.meta.glob(${JSON.stringify(globPatterns)}, { eager: true });
                                            if (import.meta.env.DEV) {
                                                console.log('[astro-routify] Auto-discovered ' + Object.keys(modules).length + ' route modules');
                                            }
                                        `;
                                    }
                                    return null;
                                },
                                transform(code, id) {
                                    // Automatically inject the auto-register import into files that call createRouter
                                    // but only if they don't already have it and it's not a node_module.
                                    if (
                                        !id.includes('node_modules') && 
                                        /createRouter\s*\(/.test(code) && 
                                        !code.includes(virtualModuleId)
                                    ) {
                                        if (debug) {
                                            console.log(`\x1b[36m[astro-routify]\x1b[0m Injecting auto-register into ${id}`);
                                        }
                                        return {
                                            code: `import "${virtualModuleId}";\n${code}`,
                                            map: null
                                        };
                                    }
                                    return null;
                                }
                            }
                        ]
                    }
                });
            }
        }
    };
}
